### ISSUE TITLE
转发合并消息发送失败后，没有转成直接发送

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [SlightDust/travelpolicy_HoshinoBot#1]

**Comment by SlightDust** [comment]
闭眼开车，有log吗。
有没有一种可能，直接发送也被风控了

**Comment by Zoe-Wh1t3zZ** [comment]
今天好了，昨天估计就转发消息一直风控



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月23日(周三) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SlightDust/travelpolicy_HoshinoBot] 转发合并消息发送失败后，没有转成直接发送 (Issue #1)




 
闭眼开车，有log吗。
 有没有一种可能，直接发送也被风控了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
